name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
          username: '${{ secrets.DOCKER_ACCOUNT }}'
          password: '${{ secrets.DOCKER_TOKEN }}'
      
    - uses: actions/checkout@v2
      
